### ISSUE TITLE
IOS: Unsupported JavaScript Result Error in Quill HTML Editor for Flutter iOS App

### ISSUE THREAD

**Issue by AbdurrehmanSubhani** [the-airbender/quill_html_editor#106]
**Bug Description:**
The error prevents the correct rendering and handling of text. The issue is related to the execution of JavaScript within the WKWebView component, which is utilized by this package. Specifically, when attempting to set the editor's text, the JavaScript execution returns a result of an unsupported type, resulting in an error.

**To Reproduce**
1. Create a new Flutter project.
2. Paste the example main.dart code.
3. Run application on IOS.

**Expected Behavior:**
The package should function correctly, allowing users to edit and render text without any errors. JavaScript execution should not return unsupported types, and text changes should be handled smoothly within the editor.

**Screenshots:**
![image](https://github.com/the-airbender/quill_html_editor/assets/53292031/dbbbcc78-619d-4665-b02e-89db5764e108)

**Smartphone:**
- Device: Iphone XR
- OS: IOS 16.5

**Flutter Doctor:**
Last login: Wed Jul 26 09:50:14 on console
(base) abdurrehmansubhani@Abdurrehmans-MacBook-Pro ~ % flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.5, on macOS 13.0 22A380 darwin-arm64, locale
    en-PK)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] IntelliJ IDEA Community Edition (version 2022.3)
[✓] IntelliJ IDEA Community Edition (version 2023.1)
[✓] VS Code (version 1.80.0)
[✓] Connected device (5 available)
    ! Error: Abdurrehman’s Apple Watch needs to connect to determine its
      availability. Check the connection between the device and its companion
      iPhone, and the connection between the iPhone and Xcode. Both devices may
      also need to be restarted and unlocked. (code 1)
[✓] Network resources

• No issues found!

**Additional Context:**

Xcode error logs:

2023-07-31 13:32:05.207435+0500 Runner[35838:3829683] Metal API Validation Enabled
2023-07-31 13:32:05.841963+0500 Runner[35838:3829683] [VERBOSE-2:FlutterDarwinContextMetalImpeller.mm(35)] Using the Impeller rendering backend.
2023-07-31 13:32:05.871871+0500 Runner[35838:3829853] 10.12.0 - [FirebaseCore][I-COR000005] No app has been configured yet.
2023-07-31 13:32:07.832377+0500 Runner[35838:3829862] flutter: widget text change
2023-07-31 13:32:07.832474+0500 Runner[35838:3829862] flutter: listening to
2023-07-31 13:32:07.850739+0500 Runner[35838:3829862] flutter: has focus true
2023-07-31 13:32:07.873993+0500 Runner[35838:3829862] flutter: index 0, range 0
2023-07-31 13:32:07.876704+0500 Runner[35838:3829862] flutter: Editor resized 200.0
2023-07-31 13:32:07.925206+0500 Runner[35838:3829683] Successfully load keyboard extensions
2023-07-31 13:32:08.018876+0500 Runner[35838:3829862] flutter: Editor has been loaded
2023-07-31 13:32:08.018995+0500 Runner[35838:3829862] flutter: Editor Loaded :)
2023-07-31 13:32:08.039116+0500 Runner[35838:3829862] flutter: Editor resized 200.0
2023-07-31 13:32:08.069473+0500 Runner[35838:3829862] flutter: widget text change <h1>Hello</h1><p>This is a quill html editor example 😊</p>
2023-07-31 13:32:08.069576+0500 Runner[35838:3829862] flutter: listening to <h1>Hello</h1><p>This is a quill html editor example 😊</p>
2023-07-31 13:32:08.097846+0500 Runner[35838:3829862] [VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(FWFEvaluateJavaScriptError, Failed evaluating JavaScript., JavaScript execution returned a result of an unsupported type (WKErrorDomain:5:{NSLocalizedDescription: JavaScript execution returned a result of an unsupported type}), null)
#0      WKWebViewHostApiImpl.evaluateJavaScriptForInstances (package:webview_flutter_wkwebview/src/web_kit/web_kit_api_impls.dart:1061)
<asynchronous suspension>
#1      WebKitWebViewController.runJavaScriptReturningResult (package:webview_flutter_wkwebview/src/webkit_webview_controller.dart:414)
<asynchronous suspension>
#2      WebViewXController.callJsMethod (package:quill_html_editor/src/widgets/webviewx/src/controller/impl/mobile.dart:124)
<asynchronous suspension>
#3      QuillHtmlEditorState._setHtmlTextToEditor (package:quill_html_editor/src/quill_editor_wrapper.dart:375)
<asynchronous suspension>
2023-07-31 13:32:08.098241+0500 Runner[35838:3829862] flutter: widget text change <p>Testing text on load</p>
2023-07-31 13:32:08.098383+0500 Runner[35838:3829862] flutter: listening to <p>Testing text on load</p>
2023-07-31 13:32:08.098618+0500 Runner[35838:3829862] flutter: An error occurred while setting text PlatformException(FWFEvaluateJavaScriptError, Failed evaluating JavaScript., JavaScript execution returned a result of an unsupported type (WKErrorDomain:5:{NSLocalizedDescription: JavaScript execution returned a result of an unsupported type}), null)

**Comment by the-airbender** [comment]
Hello @AbdurrehmanSubhani,

I have tested this on iPhone SE3, iOS 16.6 and I am unable to recreate this issue.  Could you please try it out with the latest version 2.2.3 and confirm if you are still facing the issue?

Thanks :)

**Comment by the-airbender** [comment]
Hello @AbdurrehmanSubhani ,

Please feel free to reopen the issue if you still see any problems

Thanks :)
