### ISSUE TITLE
[BUG] PlatformException unregistered_view_type

### ISSUE THREAD

**Issue by komakur** [the-airbender/quill_html_editor#183]
**Describe the bug**
ERROR: PlatformException(unregistered_view_type, A UIKitView widget is trying to create a PlatformView with an unregistered type: < plugins.flutter.io/webview >, If you are the author of the PlatformView, make sure `registerViewFactory` is invoked.

**To Reproduce**
1. Just added `ToolBar` and `QuillHtmlEditor`
```
ToolBar(controller: _controller),
const SizedBox(height: 10),
QuillHtmlEditor(
         controller: _controller,
          text: state.value,
          minHeight: 300,
          hintText: 'Write your text here',
          isEnabled: state.enabled,
),
```
It just gives error and only loading indicator is being shown:
<details><summary>Error</summary>
<p>

```
flutter: ERROR: PlatformException(unregistered_view_type, A UIKitView widget is trying to create a PlatformView with an unregistered type: < plugins.flutter.dev/pointer_interceptor_ios >, If you are the author of the PlatformView, make sure `registerViewFactory` is invoked.
See: https://docs.flutter.dev/development/platform-integration/platform-views#on-the-platform-side-1 for more details.
If you are not the author of the PlatformView, make sure to call `GeneratedPluginRegistrant.register`., null)
StackTrace: #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:651:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334:18)
<asynchronous suspension>
#2      PlatformViewsService.initUiKitView (package:flutter/src/services/platform_views.dart:243:5)
<asynchronous suspension>
#3      _DarwinViewState._createNewUiKitView (package:flutter/src/widgets/platform_view.dart:671:36)
<asynchronous suspension>
```

</p>
</details> 

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: Iphone 15 Pro (ios simulator)
 - OS: com.apple.CoreSimulator.SimRuntime.iOS-17-2

**Flutter Doctor**
<details><summary>Details</summary>
<p>

```shell
[✓] Flutter (Channel stable, 3.19.0, on macOS 14.4.1 23E224 darwin-x64, locale en-UA)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] VS Code (version 1.88.1)
[✓] Connected device (3 available)
[✓] Network resources

! Doctor found issues in 2 categories.
``` 
</p>
</details>

**Comment by onurcagilci** [comment]
How did you solve this problem? Can you explain your solution?

**Comment by cengizxturkes** [comment]
I'm waiting for solution.
